### ISSUE TITLE
not saving words in the directory

### ISSUE THREAD

**Issue by dabasjayant** [Melissa-AI/Margaery#1]
I just went through it and on running the 'main.py' file the directory is created but words are not saved. 
This might be due to 
`words_list.remove('results.wav')`
 but after removing this line it's working leaving an error 
`Melissa thinks you said what
Traceback (most recent call last):
  File "/Users/cypher/Downloads/Margaery-master/main.py", line 40, in <module>
    os.remove('results.wav')
FileNotFoundError: [Errno 2] No such file or directory: 'results.wav'`
because of the last line. What is the use of 'results.wav' here?

Also, the database is too simple to be of much use. It needs a little more functionality, to begin with

I will share if I come up with something!

**Comment by dabasjayant** [comment]
If you know how to arrange diphone dictionary then please share..

**Comment by tanay1337** [comment]
Hi @Jayant11, thanks for your interest but I am no longer maintaining this repository.

Best,
Tanay
